# Generated by Django 4.1 on 2023-03-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Surface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface_type", models.CharField(max_length=50)),
                ("surface_image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
